"""
Geometrical metrics from an RTSTRUCT.

Geometry is computed in the contours' native per-slice polygon representation
(via Shapely) rather than by rasterising onto a voxel grid. This avoids voxel
quantisation of the surface and keeps every metric in true patient coordinates:

    - volume   : planimetry, sum(slice_area * slice_thickness)
    - Dice     : exact per-slice polygon intersection, summed over shared planes
    - centroid : volume-weighted across slices
    - surface-to-surface distance (min and HD95) : nearest-neighbour distances
      between the two structures' contour boundary point clouds

The referenced image set provides the authoritative slice thickness (its
ImagePositionPatient grid) and is checked for axial acquisition: the planimetry
groups contour points into constant-z slices, which is only valid when the slice
normal runs along z. Oblique series are rejected.

Multiple contours on a single slice are resolved with the even-odd fill rule
(nested rings -> holes, disjoint rings -> union), the conventional interpretation
for DICOM planar contours.

Dependencies beyond the existing module: numpy, shapely, scipy, pydicom. The
pure helpers below are stateless and can live in a geometry utility module.

Note: 
    This code was generated by Claude Opus 4.8
"""

import glob
import os
from dataclasses import dataclass
from functools import reduce
from typing import Iterator, Optional

import numpy as np
import pydicom
from scipy.spatial import cKDTree
from shapely.geometry import Polygon
from shapely.geometry.base import BaseGeometry

# --- Classification rules -------------------------------------------------

TARGET_TOKEN = "TV"                       # GTV / CTV / PTV / ITV all contain 'TV'
EXCLUDED_NAME_TOKENS = ("BODY", "EXTERNAL")
EXCLUDED_ROI_TYPES = ("EXTERNAL",)        # RTROIInterpretedType backstop

ROLE_TARGET = "TARGET"
ROLE_OAR = "OAR"
ROLE_EXCLUDED = "EXCLUDED"

# Round z to this many decimal places so the same image plane matches across
# structures (Dice and shared-plane logic rely on a common z-grid).
Z_PRECISION_DP = 2

# Acceptable deviation of the slice normal from the z axis (direction cosines).
ORIENTATION_TOLERANCE = 1e-3

# Percentile used for the (robust) Hausdorff surface distance.
HAUSDORFF_PERCENTILE = 95

# Output rounding (mm / cc), for clean storage downstream.
_VOLUME_DP = 3
_DICE_DP = 4
_DISTANCE_DP = 2


@dataclass
class StructureGeometry:
    """Per-slice geometry and derived quantities for a single ROI."""

    name: str
    role: str
    slices: dict[float, BaseGeometry]      # z (mm) -> slice polygon
    volume_mm3: float
    centroid_mm: Optional[np.ndarray]      # (x, y, z) mm, None if empty
    surface_points_mm: np.ndarray          # (N, 3) contour boundary points, mm

    @property
    def volume_cc(self) -> float:
        return self.volume_mm3 / 1000.0


# --- Pure geometry helpers ------------------------------------------------
        
def _iter_polygons(geom: BaseGeometry) -> Iterator[Polygon]:
    """Yield the Polygon components of any Shapely geometry."""
    if geom.geom_type == "Polygon":
        yield geom
    elif geom.geom_type in ("MultiPolygon", "GeometryCollection"):
        for part in geom.geoms:
            if part.geom_type == "Polygon":
                yield part


def _build_slice_polygon(rings_xy: list[np.ndarray]) -> Optional[BaseGeometry]:
    """Combine a slice's contour rings into one geometry using even-odd fill.

    Self-intersecting rings are repaired with buffer(0). Rings with fewer than
    three points cannot form a polygon and are dropped.
    """
    polygons: list[BaseGeometry] = []
    for ring in rings_xy:
        if len(ring) < 3:
            continue
        poly: BaseGeometry = Polygon(ring)
        if not poly.is_valid:
            poly = poly.buffer(0)
        if not poly.is_empty:
            polygons.append(poly)

    if not polygons:
        return None
    return reduce(lambda a, b: a.symmetric_difference(b), polygons)


def _structure_slices(coords: dict) -> dict[float, BaseGeometry]:
    """Map each z plane of a structure to its filled slice polygon."""
    slices: dict[float, BaseGeometry] = {}
    for z_str, planes in coords.items():
        z = round(float(z_str), Z_PRECISION_DP)
        rings = [
            np.asarray(plane["data"], dtype=float)[:, :2]
            for plane in planes
            if plane.get("data")
        ]
        geom = _build_slice_polygon(rings)
        if geom is None or geom.is_empty:
            continue
        # Defensive: two source planes could collapse to one rounded z.
        slices[z] = geom if z not in slices else slices[z].symmetric_difference(geom)
    return slices


def _surface_points(slices: dict[float, BaseGeometry]) -> np.ndarray:
    """Boundary point cloud (exterior + holes) of every slice, in patient mm."""
    points: list[np.ndarray] = []
    for z, geom in slices.items():
        for poly in _iter_polygons(geom):
            for ring in (poly.exterior, *poly.interiors):
                xy = np.asarray(ring.coords, dtype=float)        # (M, 2)
                points.append(np.column_stack((xy, np.full(len(xy), z))))
    return np.vstack(points) if points else np.empty((0, 3))


# --- Image-series geometry ------------------------------------------------

def _read_image_planes(image_dir: str) -> list[tuple[float, np.ndarray]]:
    """Read (z position, orientation) for each readable slice in the series."""
    planes: list[tuple[float, np.ndarray]] = []
    for path in glob.glob(os.path.join(image_dir, "**", "*"), recursive=True):
        if not os.path.isfile(path):
            continue
        try:
            ds = pydicom.dcmread(path, stop_before_pixels=True)
        except Exception:
            continue
        ipp = getattr(ds, "ImagePositionPatient", None)
        iop = getattr(ds, "ImageOrientationPatient", None)
        if ipp is not None and iop is not None:
            planes.append((float(ipp[2]), np.asarray(iop, dtype=float)))
    return planes


def _assert_axial_orientation(planes: list[tuple[float, np.ndarray]]) -> None:
    """Reject oblique series: the slice normal must run along z (constant-z slices).

    Checks |(row x col) . z| ~ 1 for every slice. In-plane axis orientation is
    irrelevant; only the constant-z assumption underpinning the planimetry is
    enforced.
    """
    z_axis = np.array([0.0, 0.0, 1.0])
    for _, iop in planes:
        normal = np.cross(iop[:3], iop[3:])
        if not np.isclose(abs(np.dot(normal, z_axis)), 1.0, atol=ORIENTATION_TOLERANCE):
            raise ValueError(
                "Image series is not axial: slice normal is not aligned to z "
                f"(ImageOrientationPatient = {iop.tolist()}). The contour "
                "planimetry requires constant-z slices."
            )


def _slice_thickness_mm(z_values: np.ndarray) -> Optional[float]:
    """Representative slice spacing (median gap) from a set of z positions."""
    z = np.unique(np.round(z_values, Z_PRECISION_DP))
    if z.size < 2:
        return None
    return float(np.median(np.diff(np.sort(z))))


# --- Structure metrics ----------------------------------------------------

def _volume_mm3(slices: dict[float, BaseGeometry], thickness: float) -> float:
    return sum(geom.area for geom in slices.values()) * thickness


def _centroid_mm(
    slices: dict[float, BaseGeometry], thickness: float, volume_mm3: float
) -> Optional[np.ndarray]:
    """Volume-weighted 3D centroid in patient coordinates (mm)."""
    if volume_mm3 <= 0:
        return None
    moment = np.zeros(3)
    for z, geom in slices.items():
        weight = geom.area * thickness
        centre = geom.centroid
        moment += np.array([centre.x, centre.y, z]) * weight
    return moment / volume_mm3


def _dice(a: StructureGeometry, b: StructureGeometry, thickness: float) -> float:
    """Dice coefficient: 2|A and B| / (|A| + |B|), via per-slice intersection."""
    denom = a.volume_mm3 + b.volume_mm3
    if denom <= 0:
        return 0.0
    intersection_area = sum(
        a_geom.intersection(b.slices[z]).area
        for z, a_geom in a.slices.items()
        if z in b.slices
    )
    return 2.0 * (intersection_area * thickness) / denom

def _relative_overlap(a: StructureGeometry, b: StructureGeometry, thickness: float) -> float:
    """Relative overlap of target to OAR: |A and B| / |B|, via per-slice intersection."""
    sum_area = a.volume_mm3 + b.volume_mm3
    if sum_area <= 0:
        return 0.0
    intersection_area = sum(
        a_geom.intersection(b.slices[z]).area
        for z, a_geom in a.slices.items()
        if z in b.slices
    )
    return (intersection_area * thickness) / b.volume_mm3


def _surface_distances(
    a_points: np.ndarray, b_points: np.ndarray
) -> tuple[Optional[float], Optional[float]]:
    """Min closest-approach and HD95 surface distance (mm).

    Both are computed on the structures' contour boundary point clouds. The min
    is the nearest distance between the two surfaces. HD95 is the symmetric 95th
    percentile Hausdorff distance, max(P95(d_AB), P95(d_BA)), which suppresses
    single-point outliers relative to the strict Hausdorff maximum.
    """
    if a_points.size == 0 or b_points.size == 0:
        return None, None
    d_ab, _ = cKDTree(b_points).query(a_points)   # A surface -> nearest in B
    d_ba, _ = cKDTree(a_points).query(b_points)   # B surface -> nearest in A
    min_distance = float(min(d_ab.min(), d_ba.min()))
    hd95 = float(max(
        np.percentile(d_ab, HAUSDORFF_PERCENTILE),
        np.percentile(d_ba, HAUSDORFF_PERCENTILE),
    ))
    return min_distance, hd95


def _classify(name: str, roi_type: str) -> str:
    upper = name.upper()
    if any(tok in upper for tok in EXCLUDED_NAME_TOKENS) or roi_type.upper() in EXCLUDED_ROI_TYPES:
        return ROLE_EXCLUDED
    if TARGET_TOKEN in upper:
        return ROLE_TARGET
    return ROLE_OAR
